### ISSUE TITLE
addon should prompt users with surveys

### ISSUE THREAD

**Issue by lonnen** [mozilla/pioneer-study-online-news#6] opened 2017-09-25 22:53 UTC
we need to show four total surveys. this may be part of the study, or pop under with the survey. check with @raymak about the implementation in the net neutrality study

**Comment by lonnen** [comment] 2017-10-05 21:14
four surveys may be implemented as heartbeats targeted to this addon.

1. at outset
2. before treatment starts
3. after treatment ends
4. at conclusion

**Comment by mythmon** [comment] 2017-10-18 21:36
Duplicate of #12?

**Closed as completed by mythmon** 2017-10-18 21:36 UTC
